# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# EMAIL
simplejavamail:
  defaults:
    from:
      name: David
      address: david@deepfish.co

# DEEPFISH
deepfish:
  mail:
    sink:
      name: Deepfish Staging Sink
      address: morgandeepfish@gmail.com
  front:
    scheme: https
    host: app.deepfish.co
    port:
  aws:
    s3:
      bucket-name: deepfish-static
  typeform:
    requirement:
      public:
        name: xXPnxiZbU2nf
        company: AGTe4wv1mFAx
        email: ly9jKcRNvsiM
        firstName: KxFKEYC8yYiy
        lastName: FGiQ9GyUIgjM
        phoneNumber: CRhwm0Sq8tEx
      private:
        name: yOIKc5oHPN6K

# CALENDLY
calendly:
  talent-qualification:
    slug: _talent
    url: https://calendly.com/david-deepfish/_talent

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 5000

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# GOOGLE
google:
  apis:
    maps:
      api-key: AIzaSyBba2cErsaT5k8siR5G8bmf91hywX8R3B0

# LINKEDIN
linkedin:
  client:
    id: 86rw9g7ie1fvw5
    secret: dbwQGTgIuFJmiffh

# AWS
aws:
  accessKeyId: AKIAIMQSHSSRBOGANSYA
  secretAccessKey: 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

# PHANTOMBUSTER
phantombuster:
  client:
    api-key: d3LSRz7RiFeHw9pGyRe8VnXiNMExgY0F
  agents:
    linkedin-profile-scraper:
      id: 61714

# ===================================================================
# SPRING
# ===================================================================

spring:
  sendgrid:
    api-key: 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
  # ----------------------------------------
  # WEB PROPERTIES
  # ----------------------------------------
  # MULTIPART (MultipartProperties)
  http:
    multipart:
      location: /var/tmp
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: validate
