# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# EMAIL
simplejavamail:
  defaults:
    from:
      name: Deepfish
      address: hello@deepfish.fr

# DEEPFISH
deepfish:
  mail:
    sink:
      name: Deepfish Staging Sink
      address: morgandeepfish@gmail.com
  front:
    scheme: https
    host: app.deepfish.co
    port:
  aws:
    s3:
      bucket-name: deepfish-static
  typeform:
    requirement:
      public:
        name: RHHxZfDImC8d
        company: AGTe4wv1mFAx
        email: ly9jKcRNvsiM
        firstName: KxFKEYC8yYiy
        lastName: FGiQ9GyUIgjM
        phoneNumber: CRhwm0Sq8tEx

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 5000

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# LINKEDIN
linkedin:
  client:
    id: 86rw9g7ie1fvw5
    secret: dbwQGTgIuFJmiffh

# AWS
aws:
  accessKeyId: AKIAIMQSHSSRBOGANSYA
  secretAccessKey: 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

# ===================================================================
# SPRING
# ===================================================================

spring:
  sendgrid:
    api-key: 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
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: validate
