# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# LOGGING
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool.hbm2ddl: DEBUG
        type: TRACE

# EMAIL
simplejavamail:
  smtp:
    host: smtp.gmail.com
    port: 587
    password: d33pfish
    username: morgandeepfish@gmail.com
  defaults:
    from:
      name: Deepfish Staging
      address: morgandeepfish@gmail.com
  transport.mode.logging.only: true

# DEEPFISH
deepfish:
  mail:
    sink:
      name: Deepfish Staging Sink
      address: deepfish-staging-sink@yopmail.com
  front:
    host: localhost
    port: 8081

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# LINKEDIN
linkedin:
  client:
    id: 77w79kdr6gql2h
    secret: 7ovNCwpTojlQLQXI

# ===================================================================
# SPRING
# ===================================================================

spring:
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # DATASOURCE (DataSourceAutoConfiguration, DataSourceProperties)
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/deepfish_dev2
    username: postgres
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: validate
    #properties:
    #  javax:
    #    persistence:
    #      schema-generation:
    #        create-source: metadata
    #        scripts:
    #          action: create
    #          create-target: create.sql
