# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# LOGGING
logging:
  level:
    org:
      springframework: INFO

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

security:
  basic:
    enabled: false
  ignored: /**
  oauth2:
    resource:
      id: oauth2_id

# ===================================================================
# SPRING
# ===================================================================

spring:
  # ----------------------------------------
  # WEB PROPERTIES
  # ----------------------------------------
  # JACKSON (JacksonProperties)
  jackson:
    serialization:
      fail-on-empty-beans: false
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  data:
    # DATA REST (RepositoryRestProperties)
    rest:
      detection-strategy: annotated
