# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# EMAIL
simplejavamail:
  defaults:
    from:
      name: Deepfish Staging
      address: morgandeepfish@gmail.com

# DEEPFISH
deepfish:
  mail:
    sink:
      name: Deepfish Staging Sink
      address: morgandeepfish@gmail.com
  front:
    host: deepfish-app-staging.s3-website.eu-west-3.amazonaws.com
    port: 80

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 5000

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# LINKEDIN
linkedin:
  client:
    id: 77w79kdr6gql2h
    secret: 7ovNCwpTojlQLQXI

# ===================================================================
# SPRING
# ===================================================================

spring:
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: create
