# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# LOGGING
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool.hbm2ddl: DEBUG
        type: TRACE

# DEEPFISH
deepfish:
  front:
    host: localhost
    port: 8081

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# LINKEDIN
linkedin:
  client:
    id: 77w79kdr6gql2h
    secret: 7ovNCwpTojlQLQXI

# ===================================================================
# SPRING
# ===================================================================

spring:
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # DATASOURCE (DataSourceAutoConfiguration, DataSourceProperties)
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/deepfish_dev
    username: postgres
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: update
