# ===================================================================
# SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# EMAIL
simplejavamail:
  defaults:
    from:
      name: Deepfish Staging
      address: morgandeepfish@gmail.com

# DEEPFISH
deepfish:
  mail:
    sink:
      name: Deepfish Staging Sink
      address: morgandeepfish@gmail.com
  front:
    scheme: https
    host: staging-app.deepfish.co
    port:
  aws:
    s3:
      bucket-name: staging-deepfish-static
  typeform:
    requirement:
      public:
        name: MQnFNag6n7fA
        company: SidH8tvsyZVA
        email: jAYt9a0QjBuS
        firstName: Zk45wzUmywQK
        lastName: HtwdhlrLTFwG
        phoneNumber: ak11MMqGNqic
      private:
        name: wdo2wQmWh1lv

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 5000

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------

# LINKEDIN
linkedin:
  client:
    id: 77w79kdr6gql2h
    secret: 7ovNCwpTojlQLQXI

# AWS
aws:
  accessKeyId: AKIAIMQSHSSRBOGANSYA
  secretAccessKey: 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

# ===================================================================
# SPRING
# ===================================================================

spring:
  sendgrid:
    api-key: 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
  # ----------------------------------------
  # DATA PROPERTIES
  # ----------------------------------------
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: validate
