logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool.hbm2ddl: DEBUG
        type: TRACE
      springframework:
        #boot:
          #autoconfigure:
            #security: INFO
        web: INFO
security:
  basic:
    enabled: false
  ignored: /**
  oauth2:
    resource:
      id: oauth2_id
spring:
  data:
    rest:
      detection-strategy: annotated
  datasource:
    url: jdbc:postgresql://localhost:5432/deepfish_dev
    username: postgres
    password: postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smddtp.gmail.com
    port: 587
    username: morgandeepfish@gmail.com
    password: d33pfish
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true